---
- name: Pre-Flight - Install packages and pip dependencies
  hosts: openshift
  become: true
  roles:
    - role: pre-flight
      tags: 
        - pre-flight

- name: Install and Configure Apache Webserver
  hosts: openshift
  become: true
  roles:
    - role: httpd
      tags: 
        - httpd

- name: Install and Configure Apache DNS
  hosts: openshift
  become: true
  roles:
    - role: dns
      tags: 
        - dns

- name: Install and Configure Apache Registry
  hosts: openshift
  become: true
  roles:
    - role: registry
      tags: 
        - registry

- name: Install and Configure Apache HAProxy
  hosts: openshift
  become: true
  roles:
    - role: haproxy
      tags: 
        - haproxy
