---

- name: pre-tasks
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install pip dependancies 
      pip:
        name: 
          - netaddr
          - passlib

- name: Install and Configure Apache Webserver
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: httpd
      tags: 
        - httpd

- name: Install and Configure Apache DNS
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: dns
      tags: 
        - dns

- name: Install and Configure Apache Registry
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: registry
      tags: 
        - registry

- name: Install and Configure Apache HAProxy
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: haproxy
      tags: 
        - haproxy
