---

- name: Install a list of packages
  yum:
    name:
      - bind
      - bind-utils
    state: present

- name: Create DNS named config file
  template:
    src: templates/config.j2
    dest: /etc/named.conf

- name: Create additional DNS file for A and SRV records
  template:
    src: templates/additionalConfigRecords.j2
    dest: /var/named/{{ base_domain }}
    owner: named
    group: named

- name: Create additional DNS file for reverse records
  template:
    src: templates/additionalConfigReverseRecords.j2
    dest: /var/named/{{ private_network_address | regex_replace('\.[^.]*$') }}.db
    owner: named
    group: named

- name: Set firewall config for dns
  firewalld:
    zone: public
    service: dns
    permanent: yes
    state: enabled
    immediate: yes

- name: Configure firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop: 
    - 53/tcp
    - 53/udp

- name: Apply appropriate selinux context
  command: restorecon -vR /var/named

- name: start dns service
  service:
    name: named
    enabled: yes
    state: started
  
